version: 2
updates:
  - directory: /
    package-ecosystem: "gomod"
    schedule:
      day: "sunday"
      interval: "weekly"
    groups:
      all:
        patterns:
          - "*"
    reviewers:
      - "darklore"
