version: "3"

tasks:
  generate-openapi:
    cmds:
      - rm -rf pkg/kafka/connect/openapi
      - openapi-generator generate -i openapi/connect_rest.yaml --git-host github.com --git-user-id darklore --git-repo-id kafka-connect-cli --package-name openapi --generator-name go --additional-properties withGoMod=false -o pkg/kafka/connect/openapi
