// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateConnectorOperation          OperationName = "CreateConnector"
	GetConnectorOperation             OperationName = "GetConnector"
	GetConnectorActiveTopicsOperation OperationName = "GetConnectorActiveTopics"
	GetConnectorConfigOperation       OperationName = "GetConnectorConfig"
	GetConnectorConfigDefOperation    OperationName = "GetConnectorConfigDef"
	GetConnectorStatusOperation       OperationName = "GetConnectorStatus"
	GetOffsetsOperation               OperationName = "GetOffsets"
	GetTaskConfigsOperation           OperationName = "GetTaskConfigs"
	GetTaskStatusOperation            OperationName = "GetTaskStatus"
	GetTasksConfigOperation           OperationName = "GetTasksConfig"
	ListConnectorPluginsOperation     OperationName = "ListConnectorPlugins"
	ListConnectorsOperation           OperationName = "ListConnectors"
	PutConnectorConfigOperation       OperationName = "PutConnectorConfig"
	ServerInfoOperation               OperationName = "ServerInfo"
	ValidateConfigsOperation          OperationName = "ValidateConfigs"
)
