// Code generated by ogen, DO NOT EDIT.

package ogen

// OperationName is the ogen operation name
type OperationName = string

const (
	GetConnectorOperation          OperationName = "GetConnector"
	GetConnectorConfigOperation    OperationName = "GetConnectorConfig"
	GetConnectorConfigDefOperation OperationName = "GetConnectorConfigDef"
	GetConnectorStatusOperation    OperationName = "GetConnectorStatus"
	GetOffsetsOperation            OperationName = "GetOffsets"
	GetTaskConfigsOperation        OperationName = "GetTaskConfigs"
	GetTaskStatusOperation         OperationName = "GetTaskStatus"
	ListConnectorPluginsOperation  OperationName = "ListConnectorPlugins"
	ServerInfoOperation            OperationName = "ServerInfo"
	ValidateConfigsOperation       OperationName = "ValidateConfigs"
)
