// Code generated by ogen, DO NOT EDIT.

package ogen

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateConnector implements createConnector operation.
//
// Create a new connector.
//
// POST /connectors
func (UnimplementedHandler) CreateConnector(ctx context.Context, req OptCreateConnectorRequest) (r *ConnectorInfoStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConnector implements getConnector operation.
//
// Get the details for the specified connector.
//
// GET /connectors/{connector}
func (UnimplementedHandler) GetConnector(ctx context.Context, params GetConnectorParams) (r *ConnectorInfoStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConnectorActiveTopics implements getConnectorActiveTopics operation.
//
// Get the list of topics actively used by the specified connector.
//
// GET /connectors/{connector}/topics
func (UnimplementedHandler) GetConnectorActiveTopics(ctx context.Context, params GetConnectorActiveTopicsParams) (r *ConnectorActiveTopicsStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConnectorConfig implements getConnectorConfig operation.
//
// Get the configuration for the specified connector.
//
// GET /connectors/{connector}/config
func (UnimplementedHandler) GetConnectorConfig(ctx context.Context, params GetConnectorConfigParams) (r *GetConnectorConfigDefStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConnectorConfigDef implements getConnectorConfigDef operation.
//
// Get the configuration definition for the specified pluginName.
//
// GET /connector-plugins/{pluginName}/config
func (UnimplementedHandler) GetConnectorConfigDef(ctx context.Context, params GetConnectorConfigDefParams) (r *GetConnectorConfigDefDefStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// GetConnectorStatus implements getConnectorStatus operation.
//
// Get the status for the specified connector.
//
// GET /connectors/{connector}/status
func (UnimplementedHandler) GetConnectorStatus(ctx context.Context, params GetConnectorStatusParams) (r *ConnectorStateInfoStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOffsets implements getOffsets operation.
//
// Get the current offsets for the specified connector.
//
// GET /connectors/{connector}/offsets
func (UnimplementedHandler) GetOffsets(ctx context.Context, params GetOffsetsParams) (r *ConnectorOffsetsStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTaskConfigs implements getTaskConfigs operation.
//
// List all tasks and their configurations for the specified connector.
//
// GET /connectors/{connector}/tasks
func (UnimplementedHandler) GetTaskConfigs(ctx context.Context, params GetTaskConfigsParams) (r *GetTaskConfigsDefStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTaskStatus implements getTaskStatus operation.
//
// Get the state of the specified task for the specified connector.
//
// GET /connectors/{connector}/tasks/{task}/status
func (UnimplementedHandler) GetTaskStatus(ctx context.Context, params GetTaskStatusParams) (r *TaskStateStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTasksConfig implements getTasksConfig operation.
//
// Get the configuration of all tasks for the specified connector.
//
// Deprecated: schema marks this operation as deprecated.
//
// GET /connectors/{connector}/tasks-config
func (UnimplementedHandler) GetTasksConfig(ctx context.Context, params GetTasksConfigParams) (r *GetTasksConfigDefStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// ListConnectorPlugins implements listConnectorPlugins operation.
//
// List all connector plugins installed.
//
// GET /connector-plugins
func (UnimplementedHandler) ListConnectorPlugins(ctx context.Context, params ListConnectorPluginsParams) (r *ListConnectorPluginsDefStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// ListConnectors implements listConnectors operation.
//
// List all active connectors.
//
// GET /connectors
func (UnimplementedHandler) ListConnectors(ctx context.Context) (r *ListConnectorsDefStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// PutConnectorConfig implements putConnectorConfig operation.
//
// Create or reconfigure the specified connector.
//
// PUT /connectors/{connector}/config
func (UnimplementedHandler) PutConnectorConfig(ctx context.Context, req OptConnectorConfig, params PutConnectorConfigParams) (r *ConnectorInfoStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// ServerInfo implements serverInfo operation.
//
// Get details about this Connect worker and the ID of the Kafka cluster it is connected to.
//
// GET /
func (UnimplementedHandler) ServerInfo(ctx context.Context) (r *ServerInfoStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}

// ValidateConfigs implements validateConfigs operation.
//
// Validate the provided configuration against the configuration definition for the specified
// pluginName.
//
// PUT /connector-plugins/{pluginName}/config/validate
func (UnimplementedHandler) ValidateConfigs(ctx context.Context, req OptValidateConfigsReq, params ValidateConfigsParams) (r *ConfigInfosStatusCode, _ error) {
	return r, ht.ErrNotImplemented
}
